In [1]:
from random import seed

import pandas as pd
import numpy as np
import scipy.stats as ss
import random
import matplotlib.pyplot as plt
import time

In [2]:
from ImprovedDataGen import Experiment
STD_CFG  ={ "ability_df": 5,
    "prep_mean": 4.3,
    "prep_sigma": 0.7,
    "quiz_sd": 2.2,
    "quiz_mean": 6,
    "final_mean": 18.3,
    "final_sd": 2.7,
    "usage": False}
### TO CHECK FORMDE JUST TURN OFF  THE USAGE AND MANYALLY SET TWO CONFIGS
TEST_STD_CFG  ={"ability_df": 5,
    "prep_mean": 4.3,
    "prep_sigma": 0.7,
    "quiz_sd": 2.2,
    "quiz_mean": 6,
    "final_mean": 18.3,
    "final_sd": 2.7,
    "usage": True,
    "usage_mean": 3.7 ,
    "usage_sd": 1}


exp = Experiment(999666, STD_CFG, TEST_STD_CFG)

In [3]:
exp.control_data

,id,second_quiz,final_grade,prep_time,SECRET!!!!,usage
0,timothyallison@example.net,3.0,13.0,0.000000,-1.904895,0
1,voneal@example.com,8.0,20.0,74.361003,-0.638006,0
2,lunatiffany@example.org,9.0,26.0,155.068620,-0.859229,0
3,dhoward@example.org,4.0,26.0,269.650303,1.047325,0
4,brettlong@example.net,3.0,16.0,42.680877,0.737132,0
...,...,...,...,...,...,...
258,christina90@example.com,4.0,21.0,86.333581,1.829515,0
259,kcarlson@example.com,5.0,16.0,20.364085,1.124991,0
260,vsmith@example.com,4.0,16.0,124.901799,-0.054947,0
261,joshua28@example.org,10.0,24.0,42.608924,0.898672,0
262,juanjohnson@example.net,6.0,18.0,0.000000,-1.552125,0

In [4]:
exp.test_data

,id,second_quiz,final_grade,prep_time,SECRET!!!!,usage
0,richardjennifer@example.net,6.0,24.0,63.388660,0.224236,40.787146
1,loganrobin@example.net,2.0,11.0,0.000000,-1.552512,0.000000
2,ifrost@example.net,5.0,21.0,38.388135,1.421758,32.261045
3,huffmanjacob@example.com,4.0,17.0,0.000000,-1.557717,0.000000
4,alexzimmerman@example.net,2.0,17.0,64.008839,0.410050,55.817329
...,...,...,...,...,...,...
258,kristenjackson@example.com,9.0,26.0,43.417624,1.501798,33.571540
259,jessicawhite@example.com,9.0,23.0,108.996572,1.782678,108.539180
260,parkjoanna@example.net,5.0,19.0,0.000000,-1.309259,0.000000
261,xsmith@example.net,7.0,19.0,0.000000,3.331188,0.000000
262,jeffrey85@example.net,7.0,21.0,72.049283,-0.261429,68.533617

In [5]:
exp.control_data["prep_time"].mean()

np.float64(72.24329642375912)

In [6]:
exp.test_data["prep_time"].mean()

np.float64(56.51602483075702)

In [7]:
exp.test_data.to_csv("test_data.csv")

In [8]:

exp.control_data.to_csv("control_data.csv")

In [9]:
~1

-2