In [1]:
from random import seed

import pandas as pd
import numpy as np
import scipy.stats as ss
import random
import matplotlib.pyplot as plt
import time

KeyboardInterrupt:

In [4]:
from ImprovedDataGen import Experiment

STD_CFG  ={ "ability_df": 5,
    "prep_mean": 4.3,
    "prep_sigma": 0.7,
    "quiz_sd": 2.2,
    "quiz_mean": 6,
    "final_mean": 18.3,
    "final_sd": 2.7}

TEST_STD_CFG  ={"ability_df": 5,
    "prep_mean": 4.15,
    "prep_sigma": 0.7,
    "quiz_sd": 2.2,
    "quiz_mean": 6.56,
    "final_mean": 19.2,
    "final_sd": 2.7}

exp = Experiment(9999999, STD_CFG, TEST_STD_CFG)

In [5]:
exp.control_data

,id,second_quiz,final_grade,prep_time,SECRET!!!!
0,robinsonmegan@example.com,5.0,21.0,29.142336,1.324394
1,smaynard@example.com,4.0,17.0,29.269818,-0.022956
2,rgalloway@example.net,5.0,20.0,125.836475,-0.709782
3,amanda56@example.com,10.0,15.0,0.000000,-1.157319
4,ryanhoffman@example.org,4.0,20.0,0.000000,-1.206488
...,...,...,...,...,...
263,adamsrichard@example.net,6.0,18.0,78.973626,1.054199
264,moorenorma@example.com,7.0,21.0,0.000000,-1.627983
265,xjones@example.org,6.0,30.0,178.963357,-0.292919
266,bradleycollins@example.org,0.0,20.0,18.359609,1.971391
267,warrenmichael@example.org,9.0,19.0,0.000000,2.924640

In [6]:
exp.test_data

,id,second_quiz,final_grade,prep_time,SECRET!!!!
0,njohnston@example.net,7.0,23.0,85.656286,-0.450846
1,christopher17@example.net,1.0,21.0,71.418463,0.664778
2,richard18@example.com,2.0,22.0,68.634837,-0.132632
3,iedwards@example.com,8.0,21.0,0.000000,-1.131948
4,martinangela@example.com,9.0,18.0,0.000000,3.643606
...,...,...,...,...,...
245,vjohnson@example.org,8.0,22.0,39.386918,1.302731
246,stuartdakota@example.com,7.0,18.0,10.044037,-0.676334
247,padillaelizabeth@example.net,7.0,27.0,153.547778,-0.187582
248,bradleynichols@example.net,8.0,28.0,186.212642,-0.038995
249,alexandertaylor@example.com,5.0,20.0,0.000000,-1.638648

In [7]:
exp.test_data.to_csv("test_data.csv")

In [8]:

exp.control_data.to_csv("control_data.csv")